### ISSUE TITLE
Is it possible to have multiple progress meters for ComposedStopCondition?

### ISSUE THREAD

**Issue by Sid-Bhatia-0** [JuliaReinforcementLearning/ReinforcementLearningCore.jl#160]
It is possible to have multiple progress meters in the case of `ComposedStopCondition`?
I want to use both `StopAfterStep` and `StopAfterEpisode`, and stop at whichever occurs earlier. But the progress meter only shows the step-wise progress. Is it possible to also display episode-wise progress along with it?

**Comment by findmyway** [comment]
I don't know if it's possible. But it's not the scope of this package. Could you give it a try and maybe create an issue in ProgressMeters.jl?

**Comment by Sid-Bhatia-0** [comment]
Found this: [https://github.com/timholy/ProgressMeter.jl/issues/156](https://github.com/timholy/ProgressMeter.jl/issues/156)
