### ISSUE TITLE
Please create new issues in ReinforcementLearning.jl for better retrieval

### ISSUE THREAD

**Issue by findmyway** [JuliaReinforcementLearning/ReinforcementLearningCore.jl#175]
https://github.com/JuliaReinforcementLearning/ReinforcementLearning.jl/issues

**Comment by norci** [comment]
there's a little problem, that we are not able to link pull requests with issues, due to Github's restriction.

**Comment by findmyway** [comment]
Yes. We can only do it manually for now. In the future, `RLBase`, `RLCore`, `RLZoo` and `RLEnvs` will be moved to subfolders under `ReinforcementLearning.jl` and registered as sub-packages.
