### ISSUE TITLE
Type definition in update function of CircularArrayBuffer structure

### ISSUE THREAD

**Issue by felixchalumeau** [JuliaReinforcementLearning/ReinforcementLearningCore.jl#76]
Hi!

I have a doubt about the update function of the CircularArrayBuffer. The docstring mention **AbstractArray{T}** whereas the function has **AbstractArray** as a type of the data parameter. 

So I am not sure which one is a mistake.

The code is here: https://github.com/JuliaReinforcementLearning/ReinforcementLearningCore.jl/blob/master/src/utils/circular_array_buffer.jl#L161 

What do you think about it ?

**Comment by findmyway** [comment]
Sorry that the doc is not updated here. The reason that I removed the type constraint of the `data` is to allow implicit conversion here.  For example, in Atari environments, the state we read in is of type `Array{UInt8}`. And the `CircularArrayBuffer` is usually of type `AbstractArray{Float32}`. With the type constraint, we have to manually convert the data (and may need an extra allocation).

**Comment by felixchalumeau** [comment]
ok ! thanks !
