### ISSUE TITLE
Reward transformations

### ISSUE THREAD

**Issue by jbrea** [JuliaReinforcementLearning/ReinforcementLearningCore.jl#85]
Sometimes one wants to give a transformed reward to the learner, but keep the true reward given by the environment for evaluation purposes. For example Dopamine [clamps all rewards to [-1, 1]](https://github.com/google/dopamine/blob/fdb82d44550b8a7464fe71c76119279919653114/dopamine/discrete_domains/run_experiment.py#L295) and I believe some of our methods are unstable in the Atari domain, because we don't clip the rewards. Where would it be best to transform rewards? Should we add a `POST_OBSERVE` hook, or allow for applying the transformation when observations are put into buffers or just before the actual learning takes place?

**Comment by findmyway** [comment]
I think the best place to do reward transform is in the preprocessor of a wrapped env:

https://github.com/JuliaReinforcementLearning/ReinforcementLearningZoo.jl/blob/master/src/experiments/atari.jl#L27-L30

We can add a preprocessor like this (this part should be added in [RLBase](https://github.com/JuliaReinforcementLearning/ReinforcementLearningBase.jl/blob/cf2eb2b4d3aa9d6bc757eaa84fe56ae3a1f08029/src/implementations/observations.jl):

```julia
struct RewardOverriddenObs{O, R}
    obs::O
    reward::R
end

@forward RewardOverriddenObs.obs ActionStyle,
get_legal_actions,
get_legal_actions_mask,
get_terminal,
get_state

RLBase.get_reward(obs::RewardOverriddenObs) = obs.reward

clip_reward(obs) = RewardOverriddenObs(obs, clamp(get_reward(obs), -1, 1)
```

To record the real reward, ~~we need to write another custom hook~~ extend the `TotalRewardPerEpisode` (**Edit**: I'm not sure whether to make it as the default behavior, need decision):

```julia
function (hook::TotalRewardPerEpisode)(::PostActStage, agent, env, obs::RewardOverriddenObs)
    hook.reward += get_reward(obs.obs)
end
```

Thanks for reminding this. I thought it was just a trick used in NatureDQN. I'll give it a try and see if it will improve the results further.

By the way, in some implementations, `sign` is used, do you know if there's any significant difference on the result? See the one in [rlpyt](https://github.com/astooke/rlpyt/blob/35af87255465b3644747294f7fd1ff6045dab910/rlpyt/envs/atari/atari_env.py#L126)

**Comment by jbrea** [comment]
> We can add a preprocessor

Sounds good!

> I thought it was just a trick

I think it allows to use the same learning rate across different games. E.g. in pong the immediate rewards are -1, 0 or 1, whereas in other games the immediate rewards can be more than 1000. I was running IQN on a random game (time pilot) and saw it becoming unstable.

> By the way, in some implementations, sign is used, do you know if there's any significant difference on the result?

In environments where the absolute value of the reward is always larger than 1, there is obviously no difference :smile:. Whether there are atari games with smaller rewards I don't know.

Btw. not surprisingly, this reward clipping is pretty crude and [can strongly affect the results](https://deepmind.com/blog/article/preserving-outputs-precisely-while-adaptively-rescaling-targets).

**Comment by findmyway** [comment]
Thanks. I'll make a PR soon.

**Comment by findmyway** [comment]
The result of `Dopamine_Rainbow_Atari(time_pilot)` now:

![image](https://user-images.githubusercontent.com/5612003/85828418-f88cd280-b7ba-11ea-9fb8-8ce7246d8c93.png)

![image](https://user-images.githubusercontent.com/5612003/85828487-1fe39f80-b7bb-11ea-93a5-f1c4eed27ee5.png)

**Comment by jbrea** [comment]
Cool!!! I guess this is roughly comparable to [dopamine](https://google.github.io/dopamine/baselines/plots.html). I guess their 200 iterations correspond to our 50_000_000 steps. But there are many things to make it difficult to compare on Atari; for reference: https://arxiv.org/abs/1908.04683 and https://github.com/valeoai/rainbow-iqn-apex.
