### ISSUE TITLE
Implemente `StatsBase.wsample` so can sample from action space with certain probabilitly like in a policy

### ISSUE THREAD

**Issue by xiaodaigh** [JuliaReinforcementLearning/ReinforcementLearningCore.jl#94]
Currently only `rand(action_space)` is implemented. `wsample` would be nice.

**Comment by findmyway** [comment]
A more general tabular policy will be added into RLCore soon.

**Comment by findmyway** [comment]
Added in https://github.com/JuliaReinforcementLearning/ReinforcementLearningBase.jl/pull/70
